/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ClientImp;
import Controller.IClient;
import Controller.IServer;
import Controller.ServerImp;
import java.awt.Image;
import java.io.File;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.server.ServerRef;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Mohamad
 */
public class CreateGroup extends javax.swing.JFrame {

    /**
     * Creates new form CreateGroup
     */
    int pos=0;
    String path;
    IServer serverRef;
    int admin_id;
    ClientImp client;
    
    public CreateGroup() {
        initComponents();
        showImage(pos);
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }
        
    public CreateGroup(IServer server, int admin,ClientImp cl) {
        initComponents();
        showImage(pos);
        serverRef=server;
        client=cl;
        if (serverRef == null) {
            try {
                serverRef = (IServer) Naming.lookup("rmi://127.0.0.1:2000/serv");
            } catch (NotBoundException ex) {
                Logger.getLogger(ClientGui.class.getName()).log(Level.SEVERE, null, ex);
            } catch (MalformedURLException ex) {
                Logger.getLogger(ClientGui.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RemoteException ex) {
                Logger.getLogger(ClientGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        admin_id= admin;
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LImage = new javax.swing.JLabel();
        BNext = new javax.swing.JButton();
        TextGroupName = new javax.swing.JTextField();
        BCreate = new javax.swing.JButton();
        BPrevious1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 40, 40));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gabriola", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 79, -1));

        jLabel5.setFont(new java.awt.Font("Gabriola", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Profile :");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        LImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Profile/normal/none.png"))); // NOI18N
        jPanel1.add(LImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        BNext.setBackground(new java.awt.Color(161, 193, 193));
        BNext.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        BNext.setBorder(null);
        BNext.setBorderPainted(false);
        BNext.setLabel("Next");
        BNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNextActionPerformed(evt);
            }
        });
        jPanel1.add(BNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 90, 40));

        TextGroupName.setBackground(new java.awt.Color(20, 40, 40));
        TextGroupName.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        TextGroupName.setForeground(new java.awt.Color(255, 255, 255));
        TextGroupName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextGroupName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(161, 193, 193)));
        TextGroupName.setOpaque(false);
        jPanel1.add(TextGroupName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 210, 50));

        BCreate.setBackground(new java.awt.Color(161, 193, 193));
        BCreate.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        BCreate.setText("Create");
        BCreate.setBorder(null);
        BCreate.setBorderPainted(false);
        BCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BCreateMouseClicked(evt);
            }
        });
        BCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCreateActionPerformed(evt);
            }
        });
        jPanel1.add(BCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 140, 40));

        BPrevious1.setBackground(new java.awt.Color(161, 193, 193));
        BPrevious1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        BPrevious1.setText("Previous");
        BPrevious1.setBorder(null);
        BPrevious1.setBorderPainted(false);
        BPrevious1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPrevious1ActionPerformed(evt);
            }
        });
        jPanel1.add(BPrevious1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 90, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String[] getImages() {
        String path = new File("src/Images/Profile/normal").getAbsolutePath();
        File file = new File(path);
        String[] imagesList = file.list();
        return imagesList;
    }

    public void showImage(int index) {
        String[] imagesList = getImages();
        String imageName = imagesList[index];
        path = new File("src/Images/Profile/normal").getAbsolutePath();
        path = path + "/" + imageName;
        ImageIcon icon = new ImageIcon(path);
        Image image = icon.getImage().getScaledInstance(LImage.getWidth(), LImage.getHeight(), Image.SCALE_SMOOTH);
        LImage.setIcon(new ImageIcon(image));
    }
    
    
    private void BNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNextActionPerformed
        // TODO add your handling code here:
        pos = pos + 1;
        if (pos >= getImages().length) {
            pos = getImages().length - 1;
        }
        showImage(pos);
    }//GEN-LAST:event_BNextActionPerformed

    private void BCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BCreateActionPerformed

    private void BCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BCreateMouseClicked
        // TODO add your handling code here:
        try {
            String image = path.substring(path.lastIndexOf("/") + 1);
            // client
            serverRef.CreateGroup(TextGroupName.getText(), admin_id, image);
            TextGroupName.setText("");
        } catch (RemoteException ex) {
            Logger.getLogger(CreateGroup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BCreateMouseClicked

    private void BPrevious1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPrevious1ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        pos = pos - 1;
        if (pos < 0) {
            pos = 0;
        }
        showImage(pos);
    }//GEN-LAST:event_BPrevious1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateGroup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCreate;
    private javax.swing.JButton BNext;
    private javax.swing.JButton BPrevious1;
    private javax.swing.JLabel LImage;
    private javax.swing.JTextField TextGroupName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
