/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ClientImp;
import Controller.IServer;
import java.awt.Image;
import java.io.File;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.DataLayer;
import model.User;

/**
 *
 * @author Mohamad
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    IServer serverRef;
    ClientImp client;
    String path;
    boolean signUp;

    public Login() {
        initComponents();
        showImage(pos);
        PanelSinUp.setVisible(false);
        signUp = false;

        if (serverRef == null) {
            try {
                serverRef = (IServer) Naming.lookup("rmi://127.0.0.1:2000/serv");
            } catch (NotBoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (MalformedURLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RemoteException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    int pos = 0;

    public String[] getImages() {
        String path = new File("src/Images/Profile/normal").getAbsolutePath();
        File file = new File(path);
        String[] imagesList = file.list();
        return imagesList;
    }

    public void showImage(int index) {
        String[] imagesList = getImages();
        String imageName = imagesList[index];
        path = new File("src/Images/Profile/normal").getAbsolutePath();
        path = path + "/" + imageName;
        ImageIcon icon = new ImageIcon(path);
        Image image = icon.getImage().getScaledInstance(LImage.getWidth(), LImage.getHeight(), Image.SCALE_SMOOTH);
        LImage.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelSignIn = new javax.swing.JPanel();
        PanelSinUp = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TextPasswordSignUp = new javax.swing.JPasswordField();
        TextAboutSignUp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        LImage = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TextUsernameSignUp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BNext = new javax.swing.JButton();
        BPrevious = new javax.swing.JButton();
        signupbutton = new javax.swing.JButton();
        Bback1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Signin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextUsername = new javax.swing.JTextField();
        TextPassword = new javax.swing.JPasswordField();
        signupbutton1 = new javax.swing.JButton();
        BNext1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Resources/logo3.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 390, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 750));

        PanelSignIn.setBackground(new java.awt.Color(77, 155, 103));
        PanelSignIn.setLayout(null);

        PanelSinUp.setBackground(new java.awt.Color(81, 156, 106));
        PanelSinUp.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Gabriola", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Profile :");
        jLabel5.setToolTipText("");
        PanelSinUp.add(jLabel5);
        jLabel5.setBounds(10, 320, 140, 51);

        TextPasswordSignUp.setBackground(new java.awt.Color(81, 156, 106));
        TextPasswordSignUp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextPasswordSignUp.setForeground(new java.awt.Color(255, 255, 255));
        TextPasswordSignUp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextPasswordSignUp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(0, 51, 51)));
        TextPasswordSignUp.setOpaque(false);
        PanelSinUp.add(TextPasswordSignUp);
        TextPasswordSignUp.setBounds(160, 130, 310, 40);

        TextAboutSignUp.setBackground(new java.awt.Color(81, 156, 106));
        TextAboutSignUp.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        TextAboutSignUp.setForeground(new java.awt.Color(255, 255, 255));
        TextAboutSignUp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextAboutSignUp.setText("Available");
        TextAboutSignUp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(0, 51, 51)));
        PanelSinUp.add(TextAboutSignUp);
        TextAboutSignUp.setBounds(160, 200, 310, 40);

        jLabel6.setFont(new java.awt.Font("Gabriola", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Password :");
        PanelSinUp.add(jLabel6);
        jLabel6.setBounds(20, 130, 99, 51);

        LImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Profile/normal/none.png"))); // NOI18N
        PanelSinUp.add(LImage);
        LImage.setBounds(230, 260, 180, 170);

        jLabel8.setFont(new java.awt.Font("Gabriola", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(" Username :");
        PanelSinUp.add(jLabel8);
        jLabel8.setBounds(0, 60, 130, 51);

        TextUsernameSignUp.setBackground(new java.awt.Color(81, 156, 106));
        TextUsernameSignUp.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        TextUsernameSignUp.setForeground(new java.awt.Color(255, 255, 255));
        TextUsernameSignUp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextUsernameSignUp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(0, 51, 51)));
        TextUsernameSignUp.setOpaque(false);
        PanelSinUp.add(TextUsernameSignUp);
        TextUsernameSignUp.setBounds(160, 60, 310, 40);

        jLabel9.setFont(new java.awt.Font("Gabriola", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Status :");
        PanelSinUp.add(jLabel9);
        jLabel9.setBounds(40, 200, 85, 38);

        BNext.setBackground(new java.awt.Color(0, 51, 51));
        BNext.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        path = new File("src/Images/Profile/normal").getAbsolutePath();
        path = path + "/icons8-next-50.png";
        BNext.setBorder(null);
        BNext.setBorderPainted(false);
        BNext.setLabel("Next");
        BNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNextActionPerformed(evt);
            }
        });
        PanelSinUp.add(BNext);
        BNext.setBounds(330, 440, 80, 40);

        BPrevious.setBackground(new java.awt.Color(0, 51, 51));
        BPrevious.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        path = new File("src/Images/Profile/normal").getAbsolutePath();
        path = path + "/icons8-previous-50 (1).png";
        BPrevious.setBorder(null);
        BPrevious.setBorderPainted(false);
        BPrevious.setLabel("Previous");
        BPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPreviousActionPerformed(evt);
            }
        });
        PanelSinUp.add(BPrevious);
        BPrevious.setBounds(240, 440, 80, 40);

        signupbutton.setBackground(new java.awt.Color(0, 51, 51));
        signupbutton.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        signupbutton.setText("Sign up");
        signupbutton.setBorder(null);
        signupbutton.setBorderPainted(false);
        signupbutton.setFocusPainted(false);
        signupbutton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        signupbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbuttonActionPerformed(evt);
            }
        });
        PanelSinUp.add(signupbutton);
        signupbutton.setBounds(0, 500, 490, 90);

        Bback1.setBackground(new java.awt.Color(0, 51, 51));
        Bback1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        path = new File("src/Images/Profile/normal").getAbsolutePath();
        path = path + "/icons8-previous-50 (1).png";
        Bback1.setForeground(new java.awt.Color(255, 255, 255));
        Bback1.setText("<-");
        Bback1.setBorder(null);
        Bback1.setBorderPainted(false);
        Bback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bback1ActionPerformed(evt);
            }
        });
        PanelSinUp.add(Bback1);
        Bback1.setBounds(10, 0, 30, 30);

        jLabel7.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Back");
        PanelSinUp.add(jLabel7);
        jLabel7.setBounds(50, 0, 50, 30);

        PanelSignIn.add(PanelSinUp);
        PanelSinUp.setBounds(0, 160, 490, 590);

        Signin.setBackground(new java.awt.Color(0, 51, 51));
        Signin.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        Signin.setText("Sign in");
        Signin.setBorder(null);
        Signin.setBorderPainted(false);
        Signin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Signin.setFocusPainted(false);
        Signin.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Signin.setOpaque(false);
        Signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigninActionPerformed(evt);
            }
        });
        PanelSignIn.add(Signin);
        Signin.setBounds(0, 570, 490, 90);

        jLabel2.setFont(new java.awt.Font("Great Vibes", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome !");
        PanelSignIn.add(jLabel2);
        jLabel2.setBounds(130, 40, 250, 90);

        jLabel3.setFont(new java.awt.Font("Great Vibes", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Password :");
        PanelSignIn.add(jLabel3);
        jLabel3.setBounds(0, 390, 130, 30);

        jLabel4.setFont(new java.awt.Font("Great Vibes", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(" Username :");
        PanelSignIn.add(jLabel4);
        jLabel4.setBounds(0, 290, 130, 30);

        TextUsername.setBackground(new java.awt.Color(77, 155, 103));
        TextUsername.setFont(new java.awt.Font("Harlow Solid Italic", 0, 24)); // NOI18N
        TextUsername.setForeground(new java.awt.Color(255, 255, 255));
        TextUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(0, 51, 51)));
        PanelSignIn.add(TextUsername);
        TextUsername.setBounds(130, 280, 360, 50);

        TextPassword.setBackground(new java.awt.Color(77, 155, 103));
        TextPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextPassword.setForeground(new java.awt.Color(255, 255, 255));
        TextPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(0, 51, 51)));
        PanelSignIn.add(TextPassword);
        TextPassword.setBounds(130, 380, 360, 50);

        signupbutton1.setBackground(new java.awt.Color(0, 51, 51));
        signupbutton1.setFont(new java.awt.Font("Gabriola", 0, 36)); // NOI18N
        signupbutton1.setText("Sign up");
        signupbutton1.setBorder(null);
        signupbutton1.setBorderPainted(false);
        signupbutton1.setFocusPainted(false);
        signupbutton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        signupbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbutton1ActionPerformed(evt);
            }
        });
        PanelSignIn.add(signupbutton1);
        signupbutton1.setBounds(0, 660, 490, 90);

        BNext1.setBackground(new java.awt.Color(0, 51, 51));
        BNext1.setFont(new java.awt.Font("Great Vibes", 0, 24)); // NOI18N
        BNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Resources/icons8-close-window-50.png"))); // NOI18N
        BNext1.setBorder(null);
        BNext1.setBorderPainted(false);
        BNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNext1ActionPerformed(evt);
            }
        });
        PanelSignIn.add(BNext1);
        BNext1.setBounds(440, 10, 40, 40);

        getContentPane().add(PanelSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 490, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbuttonActionPerformed
        // TODO add your handling code here:
        try {
            String image = path.substring(path.lastIndexOf("/") + 1);
            if (!TextUsernameSignUp.getText().equals("") && !TextPasswordSignUp.getText().equals("")) {
                if(serverRef.CheckUsernameTaken(TextUsernameSignUp.getText())==false){
                User user = new User(TextUsernameSignUp.getText(), TextPasswordSignUp.getText(), TextAboutSignUp.getText(), image);
                serverRef.signUp(user);
                PanelSinUp.setVisible(false);
                signUp = false;
                }
                else{
                JOptionPane.showMessageDialog(null, "Username is taken");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please fill the empty fields");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_signupbuttonActionPerformed

    private void signupbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbutton1ActionPerformed
        // TODO add your handling code here:
        if (signUp == false) {
            signUp = true;
            PanelSinUp.setVisible(true);
            TextUsernameSignUp.setText("");
            TextPasswordSignUp.setText("");
            TextAboutSignUp.setText("Available");
        }
    }//GEN-LAST:event_signupbutton1ActionPerformed

    private void SigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigninActionPerformed
        //check user
        boolean correct=false;
        User user = new User(TextUsername.getText(), TextPassword.getText());
        try {
            correct=serverRef.signIn(user);
        } catch (RemoteException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (correct == true){
            DataLayer dl=new DataLayer();
            user.setId(User.CheckUser(dl, user.getUsername()));
            user.GetUserDataByID(dl);
            ClientGui c=new ClientGui(user);
            c.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Wrong combination. Please try again !");
        }
        // connect client
    }//GEN-LAST:event_SigninActionPerformed

    private void Bback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bback1ActionPerformed
        // TODO add your handling code here:
        PanelSinUp.setVisible(false);
        signUp = false;
    }//GEN-LAST:event_Bback1ActionPerformed

    private void BNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNext1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BNext1ActionPerformed

    private void BNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNextActionPerformed
        // TODO add your handling code here:
        pos = pos + 1;
        if (pos >= getImages().length) {
            pos = getImages().length - 1;
        }
        showImage(pos);
    }//GEN-LAST:event_BNextActionPerformed

    private void BPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPreviousActionPerformed
        // TODO add your handling code here:
        pos = pos - 1;
        if (pos < 0) {
            pos = 0;
        }
        showImage(pos);
    }//GEN-LAST:event_BPreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BNext;
    private javax.swing.JButton BNext1;
    private javax.swing.JButton BPrevious;
    private javax.swing.JButton Bback1;
    private javax.swing.JLabel LImage;
    private javax.swing.JPanel PanelSignIn;
    private javax.swing.JPanel PanelSinUp;
    private javax.swing.JButton Signin;
    private javax.swing.JTextField TextAboutSignUp;
    private javax.swing.JPasswordField TextPassword;
    private javax.swing.JPasswordField TextPasswordSignUp;
    private javax.swing.JTextField TextUsername;
    private javax.swing.JTextField TextUsernameSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton signupbutton;
    private javax.swing.JButton signupbutton1;
    // End of variables declaration//GEN-END:variables
}
